server:
  port: 9001 #服务端口

spring:
  application:
    name: core-user #服务名称
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.124.128:3306/maomao_mall_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '#Aa19932909'
  #redis配置
  redis:
    host: 192.168.124.128
    port: 6379
    database: 0
  #应用版本号
  ver: 1.0

auth:
  #token认证
  token:
    expireTime: -1
    strategy: RSA
