server:
  port: 9011 #服务端口

spring:
  application:
    name: core-order #服务名称
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/maomao_mall_order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'a19932909'
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: gdng-core-order-procedure
        register: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-critical-timeout: 60s
        heartbeat:
          enabled: true
