server:
  port: 9011 #服务端口

spring:
  application:
    name: core-order #服务名称
  #数据源配置
  datasource:
    url: jdbc:mysql://192.168.124.128:3306/maomao_mall_order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '#Aa19932909'
  #redis配置
  redis:
    host: 192.168.124.128
    port: 6379
    database: 0
  cloud:
    consul:
      # consul注册中心地址
      host: localhost
      # consul注册中心端口
      port: 8500
      discovery:
        # 执行注册当前服务的服务名称  默认：${spring.application.name}
        service-name: ${spring.application.name}
        # 注册时是否使用本机ip注册(不配置就是主机名)
        prefer-ip-address: true
